/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as WatershedWebcloudRunIdRouteImport } from './routes/watershed.$webcloudRunId'
import { Route as AboutWeppCloudRouteImport } from './routes/about/wepp-cloud'
import { Route as AboutWeppRouteImport } from './routes/about/wepp'
import { Route as AboutWatarRouteImport } from './routes/about/watar'
import { Route as AboutScenariosRouteImport } from './routes/about/scenarios'
import { Route as AboutSbsRouteImport } from './routes/about/sbs'
import { Route as AboutRhessysRouteImport } from './routes/about/rhessys'
import { Route as WatershedKeyWatershedKeyRouteImport } from './routes/watershed.key.$watershedKey'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const WatershedWebcloudRunIdRoute = WatershedWebcloudRunIdRouteImport.update({
  id: '/watershed/$webcloudRunId',
  path: '/watershed/$webcloudRunId',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutWeppCloudRoute = AboutWeppCloudRouteImport.update({
  id: '/wepp-cloud',
  path: '/wepp-cloud',
  getParentRoute: () => AboutRoute,
} as any)
const AboutWeppRoute = AboutWeppRouteImport.update({
  id: '/wepp',
  path: '/wepp',
  getParentRoute: () => AboutRoute,
} as any)
const AboutWatarRoute = AboutWatarRouteImport.update({
  id: '/watar',
  path: '/watar',
  getParentRoute: () => AboutRoute,
} as any)
const AboutScenariosRoute = AboutScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AboutRoute,
} as any)
const AboutSbsRoute = AboutSbsRouteImport.update({
  id: '/sbs',
  path: '/sbs',
  getParentRoute: () => AboutRoute,
} as any)
const AboutRhessysRoute = AboutRhessysRouteImport.update({
  id: '/rhessys',
  path: '/rhessys',
  getParentRoute: () => AboutRoute,
} as any)
const WatershedKeyWatershedKeyRoute =
  WatershedKeyWatershedKeyRouteImport.update({
    id: '/watershed/key/$watershedKey',
    path: '/watershed/key/$watershedKey',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/team': typeof TeamRoute
  '/about/rhessys': typeof AboutRhessysRoute
  '/about/sbs': typeof AboutSbsRoute
  '/about/scenarios': typeof AboutScenariosRoute
  '/about/watar': typeof AboutWatarRoute
  '/about/wepp': typeof AboutWeppRoute
  '/about/wepp-cloud': typeof AboutWeppCloudRoute
  '/watershed/$webcloudRunId': typeof WatershedWebcloudRunIdRoute
  '/about/': typeof AboutIndexRoute
  '/watershed/key/$watershedKey': typeof WatershedKeyWatershedKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/team': typeof TeamRoute
  '/about/rhessys': typeof AboutRhessysRoute
  '/about/sbs': typeof AboutSbsRoute
  '/about/scenarios': typeof AboutScenariosRoute
  '/about/watar': typeof AboutWatarRoute
  '/about/wepp': typeof AboutWeppRoute
  '/about/wepp-cloud': typeof AboutWeppCloudRoute
  '/watershed/$webcloudRunId': typeof WatershedWebcloudRunIdRoute
  '/about': typeof AboutIndexRoute
  '/watershed/key/$watershedKey': typeof WatershedKeyWatershedKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/team': typeof TeamRoute
  '/about/rhessys': typeof AboutRhessysRoute
  '/about/sbs': typeof AboutSbsRoute
  '/about/scenarios': typeof AboutScenariosRoute
  '/about/watar': typeof AboutWatarRoute
  '/about/wepp': typeof AboutWeppRoute
  '/about/wepp-cloud': typeof AboutWeppCloudRoute
  '/watershed/$webcloudRunId': typeof WatershedWebcloudRunIdRoute
  '/about/': typeof AboutIndexRoute
  '/watershed/key/$watershedKey': typeof WatershedKeyWatershedKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/team'
    | '/about/rhessys'
    | '/about/sbs'
    | '/about/scenarios'
    | '/about/watar'
    | '/about/wepp'
    | '/about/wepp-cloud'
    | '/watershed/$webcloudRunId'
    | '/about/'
    | '/watershed/key/$watershedKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/team'
    | '/about/rhessys'
    | '/about/sbs'
    | '/about/scenarios'
    | '/about/watar'
    | '/about/wepp'
    | '/about/wepp-cloud'
    | '/watershed/$webcloudRunId'
    | '/about'
    | '/watershed/key/$watershedKey'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/team'
    | '/about/rhessys'
    | '/about/sbs'
    | '/about/scenarios'
    | '/about/watar'
    | '/about/wepp'
    | '/about/wepp-cloud'
    | '/watershed/$webcloudRunId'
    | '/about/'
    | '/watershed/key/$watershedKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  TeamRoute: typeof TeamRoute
  WatershedWebcloudRunIdRoute: typeof WatershedWebcloudRunIdRoute
  WatershedKeyWatershedKeyRoute: typeof WatershedKeyWatershedKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/watershed/$webcloudRunId': {
      id: '/watershed/$webcloudRunId'
      path: '/watershed/$webcloudRunId'
      fullPath: '/watershed/$webcloudRunId'
      preLoaderRoute: typeof WatershedWebcloudRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/wepp-cloud': {
      id: '/about/wepp-cloud'
      path: '/wepp-cloud'
      fullPath: '/about/wepp-cloud'
      preLoaderRoute: typeof AboutWeppCloudRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/wepp': {
      id: '/about/wepp'
      path: '/wepp'
      fullPath: '/about/wepp'
      preLoaderRoute: typeof AboutWeppRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/watar': {
      id: '/about/watar'
      path: '/watar'
      fullPath: '/about/watar'
      preLoaderRoute: typeof AboutWatarRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/scenarios': {
      id: '/about/scenarios'
      path: '/scenarios'
      fullPath: '/about/scenarios'
      preLoaderRoute: typeof AboutScenariosRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/sbs': {
      id: '/about/sbs'
      path: '/sbs'
      fullPath: '/about/sbs'
      preLoaderRoute: typeof AboutSbsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/rhessys': {
      id: '/about/rhessys'
      path: '/rhessys'
      fullPath: '/about/rhessys'
      preLoaderRoute: typeof AboutRhessysRouteImport
      parentRoute: typeof AboutRoute
    }
    '/watershed/key/$watershedKey': {
      id: '/watershed/key/$watershedKey'
      path: '/watershed/key/$watershedKey'
      fullPath: '/watershed/key/$watershedKey'
      preLoaderRoute: typeof WatershedKeyWatershedKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AboutRouteChildren {
  AboutRhessysRoute: typeof AboutRhessysRoute
  AboutSbsRoute: typeof AboutSbsRoute
  AboutScenariosRoute: typeof AboutScenariosRoute
  AboutWatarRoute: typeof AboutWatarRoute
  AboutWeppRoute: typeof AboutWeppRoute
  AboutWeppCloudRoute: typeof AboutWeppCloudRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutRhessysRoute: AboutRhessysRoute,
  AboutSbsRoute: AboutSbsRoute,
  AboutScenariosRoute: AboutScenariosRoute,
  AboutWatarRoute: AboutWatarRoute,
  AboutWeppRoute: AboutWeppRoute,
  AboutWeppCloudRoute: AboutWeppCloudRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  TeamRoute: TeamRoute,
  WatershedWebcloudRunIdRoute: WatershedWebcloudRunIdRoute,
  WatershedKeyWatershedKeyRoute: WatershedKeyWatershedKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
